on:
  workflow_dispatch:
  push:
    branches:
      - "main"

permissions:
  contents: read
  packages: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: "production"
    steps:
      - uses: easimon/maximize-build-space@fc881a613ad2a34aca9c9624518214ebc21dfc0c
        with:
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
      - uses: actions/setup-go@v3
        with:
          go-version: ">=1.24.0"
      - run: go install sigs.k8s.io/kind@v0.27.0
      - run: cd ${GITHUB_WORKSPACE}/kubernetes && hack/print-workspace-status.sh
      - run: kind build node-image ${GITHUB_WORKSPACE}/kubernetes --image ghcr.io/intunderflow/taming-the-beast-kubecon-eu2025-demo/node:${GITHUB_SHA}
      - run: docker push ghcr.io/intunderflow/taming-the-beast-kubecon-eu2025-demo/node:${GITHUB_SHA}